### ISSUE TITLE
Improvements roadmap

### ISSUE THREAD

**Issue by llrs** [jdieramon/refseqR#9]
These are some improvements that would be nice to have, some of them will be required by Bioconductor reviewers others might not. Not on a specific order and each point might be addressed in several PR: 
 - [x] Fix all the warnings, errors and notes from BiocCheck and R CMD check (One of the last things to do is subscribing to bioc-devel mailing list and support.bioconductor.org site. 
 - [x] Vectorize code when possible.
 - [x] Convert from print/message("Error. ...") to stop("...")
 - [ ] Separate responsibility of each function between retrieving and saving.
 - [x] Simplify code to make it easier to read, and return multiple values when there is a loop involved. 
 - [x] Return Bioconductor classes:
   - [x] Ranges (IRanges?)
   - [x] Use Biostrings
 - [ ] Add tests to reach coverage of ~75% of code. 
 - [x] Remove usage from documentation as it is now automatically added from the functions definition.
